### ISSUE TITLE
Nao ficou muito claro a instalação

### ISSUE THREAD

**Issue by sergiomendonca** [MattBidas/magento2-reports#1]
Olá, o caminho para instalaçao nao ficou claro.
É app/code/Override/Reports/..arquivos aqui.. ???

Desse jeito nao funcionou. Nada mudou.

**Comment by marcosdsdba** [comment]
Hi

First to all
You need knowledge
Magento2 Development Systems
**Magento2 Folder's Structure** more important to understending

**Override** is a name from Magento2 Distro Name on Own: app/code /**Override**/Reports /..files
One more Example:

app / code / **MyCompanyName** / Reports.

Hope this helps!
